spring:
  application:
    name: investmentApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/investments_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update